name: Java CI

on:

  push:

    branches: [ ca7 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11

        uses: actions/setup-java@v2

        with:

          java-version: '11'

          distribution: 'true'

          cache: maven

      - name: build

        run: mvn -B package --file pom.xml

      - name: compile

        run: mvn compiler:testCompile

      - name: run

        run: mvn -Dtest=bdd.BDDEntryPointAcceptanceTest test
